/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Robles
 */
public class productosVistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public productosVistaPrincipal() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jL_frutas = new javax.swing.JLabel();
        jL_frutas1 = new javax.swing.JLabel();
        jL_frutas2 = new javax.swing.JLabel();
        jL_frutas3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProvedores = new javax.swing.JMenu();
        subMenuProvedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        subMenuRoles = new javax.swing.JMenuItem();
        subMenuEstados = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCTOS");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jL_frutas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frutas_pequenas.png"))); // NOI18N
        jL_frutas.setText("FRUTAS");
        jL_frutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutasMouseClicked(evt);
            }
        });

        jL_frutas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas1.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verduras_pequenas.png"))); // NOI18N
        jL_frutas1.setText("VERDURAS");
        jL_frutas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutas1MouseClicked(evt);
            }
        });

        jL_frutas2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas2.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/granos_pequenas.png"))); // NOI18N
        jL_frutas2.setText("GRANOS");
        jL_frutas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutas2MouseClicked(evt);
            }
        });

        jL_frutas3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas3.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuberculos_pequenas.png"))); // NOI18N
        jL_frutas3.setText("TUBERCULOS");
        jL_frutas3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutas3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_frutas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_frutas2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_frutas1)
                    .addComponent(jL_frutas3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_frutas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_frutas1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_frutas2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_frutas3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_pequeno.png"))); // NOI18N

        btnInsertar.setText("AGREGAR");
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodificarMouseClicked(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });

        jButton4.setText("BUSCAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("PRODUCTOS");

        jMenuBar1.setBorder(null);

        menuProvedores.setText("Proveedores");

        subMenuProvedores.setText("Crud");
        subMenuProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuProvedoresActionPerformed(evt);
            }
        });
        menuProvedores.add(subMenuProvedores);

        jMenuItem1.setText("Estados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProvedores.add(jMenuItem1);

        jMenuBar1.add(menuProvedores);

        jMenu2.setText("Usuarios");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        subMenuRoles.setText("Roles");
        subMenuRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRolesActionPerformed(evt);
            }
        });
        jMenu2.add(subMenuRoles);

        subMenuEstados.setText("Estados");
        subMenuEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEstadosActionPerformed(evt);
            }
        });
        jMenu2.add(subMenuEstados);

        jMenuItem4.setText("Crud");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");

        jMenuItem2.setText("Clasificación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("U. Medida");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Acerca de");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar)
                    .addComponent(jButton4))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_frutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutasMouseClicked
        proCatFrutas frutas = new proCatFrutas();
        frutas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jL_frutasMouseClicked

    private void jL_frutas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutas1MouseClicked
        proCatVerduras verduras = new proCatVerduras();
        verduras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jL_frutas1MouseClicked

    private void jL_frutas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutas2MouseClicked
        proCatGranos granos = new proCatGranos();
        granos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jL_frutas2MouseClicked

    private void jL_frutas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutas3MouseClicked
       proCatTuberculos tuberculos = new proCatTuberculos();
       tuberculos.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jL_frutas3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        proBusGeneral llamadaVista = new proBusGeneral();
        llamadaVista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Clasificacion llamadaClasificacion = new Clasificacion();
        llamadaClasificacion.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        JOptionPane.showMessageDialog(null, "Kevin Robles\nJavier Sepulveda\n           2020");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void subMenuEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEstadosActionPerformed
        Estados llamarEstado = new Estados();
        llamarEstado.setVisible(true);

    }//GEN-LAST:event_subMenuEstadosActionPerformed

    private void subMenuRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRolesActionPerformed
        Roles llamarRoles = new Roles();
        llamarRoles.setVisible(true);
    }//GEN-LAST:event_subMenuRolesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Estados llamarEstado = new Estados();
        llamarEstado.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void subMenuProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuProvedoresActionPerformed
        ingresoProvedores llamarProveedores = new  ingresoProvedores();
        llamarProveedores.setVisible(true);
    }//GEN-LAST:event_subMenuProvedoresActionPerformed

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        productoCrudAgregar agre = new productoCrudAgregar();
        agre.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void btnmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseClicked
       productoCrud mod = new productoCrud();
       mod.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnmodificarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
        productoCrud eli = new productoCrud();
       eli.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btneliminarMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        unidadMedidas umedida = new unidadMedidas();
        umedida.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Usuarios usu = new Usuarios();
        usu.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productosVistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInsertar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnmodificar;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jL_frutas;
    private javax.swing.JLabel jL_frutas1;
    private javax.swing.JLabel jL_frutas2;
    private javax.swing.JLabel jL_frutas3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuProvedores;
    private javax.swing.JMenuItem subMenuEstados;
    private javax.swing.JMenuItem subMenuProvedores;
    private javax.swing.JMenuItem subMenuRoles;
    // End of variables declaration//GEN-END:variables
}
