/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.vistasClientes;

import javax.swing.JOptionPane;
import vista.proBusGeneral;
import vista.proCatFrutas;
import vista.proCatGranos;
import vista.proCatTuberculos;
import vista.proCatVerduras;

/**
 *
 * @author Kevin Robles
 */
public class productosVistaPrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public productosVistaPrincipalCliente() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jL_frutas = new javax.swing.JLabel();
        jL_frutas1 = new javax.swing.JLabel();
        jL_frutas2 = new javax.swing.JLabel();
        jL_frutas3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCTOS");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jL_frutas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frutas_pequenas.png"))); // NOI18N
        jL_frutas.setText("FRUTAS");
        jL_frutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutasMouseClicked(evt);
            }
        });

        jL_frutas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas1.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verduras_pequenas.png"))); // NOI18N
        jL_frutas1.setText("VERDURAS");
        jL_frutas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutas1MouseClicked(evt);
            }
        });

        jL_frutas2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas2.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/granos_pequenas.png"))); // NOI18N
        jL_frutas2.setText("GRANOS");
        jL_frutas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutas2MouseClicked(evt);
            }
        });

        jL_frutas3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_frutas3.setForeground(new java.awt.Color(0, 153, 0));
        jL_frutas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuberculos_pequenas.png"))); // NOI18N
        jL_frutas3.setText("TUBERCULOS");
        jL_frutas3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_frutas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_frutas3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_frutas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_frutas2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_frutas1)
                    .addComponent(jL_frutas3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_frutas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_frutas1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_frutas2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_frutas3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_pequeno.png"))); // NOI18N

        jButton4.setText("BUSCAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("PRODUCTOS");

        jMenuBar1.setBorder(null);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 160, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_frutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutasMouseClicked
        proCatFrutasCliente frutas = new proCatFrutasCliente();
        frutas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jL_frutasMouseClicked

    private void jL_frutas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutas1MouseClicked
        proCatVerdurasCliente verduras = new proCatVerdurasCliente();
        verduras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jL_frutas1MouseClicked

    private void jL_frutas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutas2MouseClicked
        proCatGranosCliente granos = new proCatGranosCliente();
        granos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jL_frutas2MouseClicked

    private void jL_frutas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_frutas3MouseClicked
       proCatTuberculosCliente tuberculos = new proCatTuberculosCliente();
       tuberculos.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jL_frutas3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        proBusGeneralCliente llamadaVista = new proBusGeneralCliente();
        llamadaVista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productosVistaPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productosVistaPrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jL_frutas;
    private javax.swing.JLabel jL_frutas1;
    private javax.swing.JLabel jL_frutas2;
    private javax.swing.JLabel jL_frutas3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
